name: Build Recipes

on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install latest pyodide-build and build dependencies
        run : |
          pip install git+https://github.com/pyodide/pyodide.git@main#subdirectory=pyodide-build
          pip install setuptools --upgrade
          
          sudo apt update
          sudo apt install gfortran f2c
          
      - name: Check emscripten version
        run: |
          echo EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version) >> $GITHUB_ENV
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}

      - name: Build recipes
        run: |
          # TODO: fix pyodide/tools/deploy_s3.py to not compress an archive to gz
          wget http://pyodide-cache.s3-website-us-east-1.amazonaws.com/xbuildenv/dev/xbuildenv.tar.bz2 -O xbuildenv.tar.bz2.gz
          gzip -d xbuildenv.tar.bz2.gz
          mkdir .pyodide-xbuildenv
          tar -xvf xbuildenv.tar.bz2 -C .pyodide-xbuildenv
          
          pyodide xbuildenv install
          pyodide build-recipes "*" --install --install-dir=./repodata

      - name: Store artifacts build
        uses: actions/upload-artifact@v2
        with:
          name: repodata
          path: ./repodata/
          retention-days: 15

  test:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        test-config: [
          {runner: selenium, runtime: chrome, runtime-version: latest },
        ]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Download latest Pyodide
        run: |
          # TODO: fix pyodide/tools/deploy_s3.py to not compress an archive to gz
          wget http://pyodide-cache.s3-website-us-east-1.amazonaws.com/xbuildenv/dev/pyodide-core.tar.bz2 -O pyodide-core.tar.bz2.gz
          gzip -d pyodide-core.tar.bz2.gz
          tar -xvf pyodide-core.tar.bz2
          mv pyodide dist

      - uses: pyodide/pyodide-actions/install-browser@v1
        with:
          runner: ${{ matrix.test-config.runner }}
          browser: ${{ matrix.test-config.runtime }}
          browser-version: ${{ matrix.test-config.runtime-version }}

      - name: Install requirements
        shell: bash -l {0}
        run: |
          python3 -m pip install pytest pytest-pyodide pytest-httpserver

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: repodata
          path: ./repodata/

      - name: Copy repodata
        run: |
          cp ./repodata/* ./dist/

      - name: Run tests
        run: |
          pytest -v \
            --dist-dir=./dist/ \
            --runner=${{ matrix.test-config.runner }} \
            --rt ${{ matrix.test-config.runtime }} \
            packages
